### ISSUE TITLE
Peer Review: Technical issues/bugs/suggestions

### ISSUE THREAD

**Issue by SoulJason** [OneDestinys/WebTechProject#6]
Hey! Wanted to start off by saying I love the idea of a rust tutorial website, the homepage is pretty fun.

My two points of feedback for content on your site will be stated below!

1. For your buildings page, I think you should consider getting rid of your background where the text is near! It's a bit hard to focus on the content, and maybe consider adding more margins on each side or some sort of padding around the text so it's easier to digest and pay attention to. 
![image](https://user-images.githubusercontent.com/25781284/232592012-3c866985-89d5-4492-89f9-b16e127ae428.png)

2. Since the rust logo is so clean, I would consider changing the navigation bar buttons to be a bit more clean and stylistically similar to the game logo and make it look less large and boxy.
![image](https://user-images.githubusercontent.com/25781284/232592741-2ab48056-7255-4a53-a479-df377f01d608.png)

**Comment by OneDestinys** [comment]
Resolved
