### ISSUE TITLE
Peer Review: Content

### ISSUE THREAD

**Issue by SoulJason** [OneDestinys/WebTechProject#7]
I think this page has a lot of promise for content so excited how this will turn out.

1. One Thing I'd recommend is potentially not using hover as a mechanic for learning more about each weapon. I think it's a fun idea but I would at least include some information on the gun and maybe hovering to learn some fun facts. This is mostly so people can compare weapons and whatnot. 
![image](https://user-images.githubusercontent.com/25781284/232592956-0130d772-97a4-46a9-9252-175867bdc634.png)

2. Regarding information hierarchy, I recommend trying to find some way to make it obvious what information is the most important, and what information belongs under what category. I can see some captions larger and smaller, but it all kind of blends together content wise.
![image](https://user-images.githubusercontent.com/25781284/232593061-0670c642-56eb-4016-a198-016149c480df.png)

**Comment by OneDestinys** [comment]
Resolved
